from __future__ import annotations

from collections.abc import Mapping
from typing import TYPE_CHECKING, Any, TypeVar
from uuid import UUID

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..models.com_hellopublic_userapigateway_api_rest_order_api_multileg_order_request_type import (
    ComHellopublicUserapigatewayApiRestOrderApiMultilegOrderRequestType,
)

if TYPE_CHECKING:
    from ..models.com_hellopublic_userapigateway_api_rest_order_gateway_order_leg import (
        ComHellopublicUserapigatewayApiRestOrderGatewayOrderLeg,
    )
    from ..models.com_hellopublic_userapigateway_api_rest_order_order_expiration import (
        ComHellopublicUserapigatewayApiRestOrderOrderExpiration,
    )


T = TypeVar("T", bound="ComHellopublicUserapigatewayApiRestOrderApiMultilegOrderRequest")


@_attrs_define
class ComHellopublicUserapigatewayApiRestOrderApiMultilegOrderRequest:
    """Used for multileg orders placed via the UserApiGatewayService or other service where the order is just a single
    request and the orderId is generated by the client

        Attributes:
            order_id (UUID): The OrderId, a UUID conforming to RFC 4122 (8-4-4-4-12 format, e.g.,
                0d2abd8d-3625-4c83-a806-98abf35567cc), globally unique over time. Serves as the deduplication key; if reused on
                the same account, the operation is idempotent.
            quantity (int): The order quantity
            type_ (ComHellopublicUserapigatewayApiRestOrderApiMultilegOrderRequestType): The order type. Only LIMIT order
                are allowed
            limit_price (str): The limit price for the order. For debit spreads the limit price must be positive, for create
                spreads the limit price is negative
            expiration (ComHellopublicUserapigatewayApiRestOrderOrderExpiration):
            legs (list[ComHellopublicUserapigatewayApiRestOrderGatewayOrderLeg]): From 2-6 legs. There can be at most 1
                equity leg
    """

    order_id: UUID
    quantity: int
    type_: ComHellopublicUserapigatewayApiRestOrderApiMultilegOrderRequestType
    limit_price: str
    expiration: ComHellopublicUserapigatewayApiRestOrderOrderExpiration
    legs: list[ComHellopublicUserapigatewayApiRestOrderGatewayOrderLeg]
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        order_id = str(self.order_id)

        quantity = self.quantity

        type_ = self.type_.value

        limit_price = self.limit_price

        expiration = self.expiration.to_dict()

        legs = []
        for legs_item_data in self.legs:
            legs_item = legs_item_data.to_dict()
            legs.append(legs_item)

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "orderId": order_id,
                "quantity": quantity,
                "type": type_,
                "limitPrice": limit_price,
                "expiration": expiration,
                "legs": legs,
            }
        )

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.com_hellopublic_userapigateway_api_rest_order_gateway_order_leg import (
            ComHellopublicUserapigatewayApiRestOrderGatewayOrderLeg,
        )
        from ..models.com_hellopublic_userapigateway_api_rest_order_order_expiration import (
            ComHellopublicUserapigatewayApiRestOrderOrderExpiration,
        )

        d = dict(src_dict)
        order_id = UUID(d.pop("orderId"))

        quantity = d.pop("quantity")

        type_ = ComHellopublicUserapigatewayApiRestOrderApiMultilegOrderRequestType(d.pop("type"))

        limit_price = d.pop("limitPrice")

        expiration = ComHellopublicUserapigatewayApiRestOrderOrderExpiration.from_dict(
            d.pop("expiration")
        )

        legs = []
        _legs = d.pop("legs")
        for legs_item_data in _legs:
            legs_item = ComHellopublicUserapigatewayApiRestOrderGatewayOrderLeg.from_dict(
                legs_item_data
            )

            legs.append(legs_item)

        com_hellopublic_userapigateway_api_rest_order_api_multileg_order_request = cls(
            order_id=order_id,
            quantity=quantity,
            type_=type_,
            limit_price=limit_price,
            expiration=expiration,
            legs=legs,
        )

        com_hellopublic_userapigateway_api_rest_order_api_multileg_order_request.additional_properties = d
        return com_hellopublic_userapigateway_api_rest_order_api_multileg_order_request

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
